##########################################################################################################
#                   Copyright © 2020, Raznar Lab, or its associates. All Rights Reserved.                #
##########################################################################################################
# More information at https://github.com/Raznar-Lab/ServerOptimizer/wiki

auto-save: 1 # Save Progress automatically every x Minutes
schedule-duration: 10 # Kill entities in unloaded chunks automatically every x Seconds
mob-movement: false # Enable Mob Move
mob-interaction: false # Enable Mob Interact
natural-spawn: false # Enable Mob Spawn Naturally
chunkload-spawn: false # Enable Mob Spawn while player loads a chunk
world: all # Enable Entity Optimizer at specified world
whitelist-mob: [] # Prevent specified Mob getting killed while Entity Optimizer is running
whitelist-tameable-mob: # Prevent specified Tameable Mob getting killed while Entity Optimizer is running
  - Wolf
  - Horse

