# More information at https://github.com/Raznar-Lab/ServerStonker/wiki
##########################################################################################################
#                   Copyright © 2020, Raznar Lab, or its associates. All Rights Reserved.                #
##########################################################################################################
blocks-radius: 48 # Prevent mobs getting killed while players are in the radius (Default: 48 / 3 Chunks)
schedule:
- duration: 30 # Kill entities in unloaded chunks automatically every x Seconds
- log: false # Logs the schedule
disable-spawn:
- natural: false # Enable Mob Spawn Naturally
- chunk: false # Enable Mob Spawn while player generates a chunk
- spawner: false # Enable Mob spawn from spawner
worlds: # Enable Entity Cleaner at specified world
  - "world"
mob-list:
  - Horse:
    - ai: true
    - tamed: true
  - Zombie:
    - ai: true
    - tamed: false
unload-chunk: true # Unload chunk when they're no players in the radius