name: ServerOptimizer
version: 1.3-Beta
main: id.raznar.serveroptimizer.Main
authors: [ xAbhista, BadAccuracyID ]
description: Make your Minecraft Server TPS STONKS in a realtime
website: https://lab.raznar.id